### ISSUE TITLE
Erstatt @navikt/next-auth-wonderwall med @navikt/oasis

### ISSUE THREAD

**Issue by karl-run** [navikt/min-ia#190]
next-auth-wonderwall is deprecated, and has been replaced by [@navikt/oasis](https://github.com/navikt/oasis)

Oasis should be more or less a drop in replacement.

Here are some example migrations:

* nextjs app-dir: https://github.com/navikt/syk-dig/pull/209/files
* nextjs pages-dir: https://github.com/navikt/sykmeldinger/pull/548/files

**Comment by karl-run** [comment]
Minner om denne @navikt/pia :smile:

**Comment by klechr** [comment]
Takker! Har lagt det inn som en oppgave på brettet vårt.

**Comment by sstensby** [comment]
Da skal dette endelig være ferdig med #197.
